FROM ubuntu:latest
MAINTAINER publicplan GmbH

# update
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get update --fix-missing

# install debug tools
RUN apt-get install -y vim
RUN apt-get install -y curl
RUN apt-get install -y net-tools dnsutils inetutils-tools inetutils-ping

# add packages
RUN apt-get install -y git openjdk-8-jdk

# install gradle required for build
RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:cwchien/gradle
RUN apt-get update
RUN apt-get install -y wget
RUN wget https://services.gradle.org/distributions/gradle-3.4.1-bin.zip
RUN mkdir /opt/gradle
RUN apt-get install -y unzip
RUN unzip -d /opt/gradle gradle-3.4.1-bin.zip
RUN PATH=$PATH:/opt/gradle/gradle-3.4.1/bin
ENV GRADLE_HOME=/opt/gradle/gradle-3.4.1
ENV PATH=$PATH:$GRADLE_HOME/bin
RUN gradle -v

# change workdir
ADD ./ /yacy_grid_parser
WORKDIR /yacy_grid_parser

# create log dir
RUN mkdir -p log

# compile
RUN gradle build
RUN mkdir data/parser-8500/conf/ -p
RUN cp docker/config-parser.properties data/parser-8500/conf/config.properties
RUN chmod +x ./docker/start.sh

# expose web interface port
EXPOSE 8500

# define default command.
ENTRYPOINT ["/bin/bash", "./docker/start.sh"]
